version: 0.2

env:
  variables:
    aws-region: us-east-1
  secrets-manager:
#    ACCESS_KEY: "aws/credentials:aws_access_key_id"
#    SECRET_KEY: "aws/credentials:aws_secret_access_key"
    API_ENDPOINT: "aws/${env}/df/api_gw"

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo REACT_APP_API_ENDPOINT=${API_ENDPOINT} >> .env
      # - npm run test
      - npm run build

      # - echo Configuring AWS Credentials and syncing changes to s3
      # - aws configure set aws_access_key_id ${ACCESS_KEY}
      # - aws configure set aws_secret_access_key ${SECRET_KEY}
      # - aws configure set default.region us-west-2
      # - aws s3 sync ./build/ s3://diamond-finishes --delete

artifacts:
  type: zip
  base-directory: "build"
  files:
  - "**/*"

badgeEnabled: true